# Generated by Django 3.2.13 on 2022-06-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220630_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='tag', max_length=255),
            preserve_default=False,
        ),
    ]
